name: CI

on: [push, pull_request]

jobs:
  linux-build:
    name: Linux CI
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
          - "ubuntu:22.04"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y \
            build-essential \
            cmake \
            libboost-program-options-dev \
            libcodec2-dev \
            libgl-dev \
            libgtest-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxrandr-dev \
            libasound2-dev \
            --no-install-recommends
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure RtAudio
        run: |
          cd thirdparty/rtaudio
          ./configure  --with-jack --with-alsa --with-pulse
          mkdir build
          cd build
          cmake ..
      - name: Compile RtAudio
        working-directory: thirdparty/rtaudio/build
        run: make -j4
      - name: Install Rtaudio
        working-directory: thirdparty/rtaudio/build
        run: make install
      - name: Configure
        working-directory: thirdparty/rtaudio/build
        run: |
          cd ../../../
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j4
      - name: Test
        working-directory: build
        run: make test
      - name: Install
        working-directory: build
        run: make install
  windows-build:
    name: Windows CI
    runs-on: "windows-2019"
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge
      - name: Setup Conda
        run: conda info
      - name: Install MSVC on Windows
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Create Conda Env
        run: conda create -n M17 vs2019_win-64 cmake ninja pkg-config boost-cpp gtest gmock gtest libcodec2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure RtAudio 
        run: |
          cd thirdparty/rtaudio
          mkdir build
          cd build
          conda activate M17
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH="D:/" -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ..
      - name: Compile RtAudio
        working-directory: thirdparty/rtaudio/build
        run: cmake --build . --config Release --
      - name: Install RtAudio
        working-directory: thirdparty/rtaudio/build
        run: ECHO F|xcopy rtaudio.dll D:\bin\rtaudio.dll
      - name: Configure
        working-directory: thirdparty/rtaudio/build
        run: |
          cd ../../../
          mkdir build
          cd build
          conda activate M17
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH="D:/" -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ..
      - name: Compile
        working-directory: build
        run: cmake --build . --config Release -- -j4
      - name: Install
        working-directory: build
        run: cmake --build . --config Release --target install
      - name: Add DLLs
        run: |
          cd C:\Miniconda3\envs\M17
          xcopy Library\bin\api-ms-win-crt-time-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-string-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-convert-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-utility-l1-1-0.dll D:\bin\
          xcopy Library\bin\libcodec2.dll D:\bin\
          xcopy Library\bin\boost_program_options.dll D:\bin\
          xcopy Library\bin\MSVCP140.dll D:\bin\
          xcopy Library\bin\VCRUNTIME140.dll D:\bin\
          xcopy Library\bin\VCRUNTIME140_1.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-runtime-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-heap-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-stdio-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-locale-l1-1-0.dll D:\bin\
          xcopy Library\bin\api-ms-win-crt-math-l1-1-0.dll D:\bin\
          xcopy Library\mingw-w64\bin\libwinpthread-1.dll D:\bin\
          xcopy Library\mingw-w64\bin\libgcc_s_seh-1.dll D:\bin\
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: M17-Tools-Win-x64
          path: D:/bin/
