name: CI

on: [push, pull_request]

jobs:
  linux-build:
    name: Linux CI
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
          - "ubuntu:22.04"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y \
            build-essential \
            cmake \
            libboost-program-options-dev \
            libcodec2-dev \
            libgl-dev \
            libgtest-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxrandr-dev \
            --no-install-recommends
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j4
      - name: Test
        working-directory: build
        run: make test
      - name: Install
        working-directory: build
        run: make install
  windows-build:
    name: Windows CI
    runs-on: "windows-2019"
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge
      - name: Setup Conda
        run: conda info
      - name: Install MSVC on Windows
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Create Conda Env
        run: conda create -n M17 vs2019_win-64 cmake ninja pkg-config boost-cpp gtest gmock gtest libcodec2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure RtAudio
        run: |
          cd thirdparty/rtaudio
          mkdir build
          cd build
          conda activate M17
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH="D:/" -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ..
      - name: Compile RtAudio
        working-directory: thirdparty/rtaudio/build
        run: cmake --build . --config Release --
      - name: Install RtAudio
        working-directory: thirdparty/rtaudio/build
        run: copy rtaudio.dll D:\\bin\\
      - name: Configure
        working-directory: thirdparty/rtaudio/build
        run: |
          cd ../../../
          mkdir build
          cd build
          conda activate M17
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH="D:/" -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ..
      - name: Compile
        working-directory: build
        run: cmake --build . --config Release --
      - name: Install
        working-directory: build
        run: cmake --build . --config Release --target install
      - name: Add DLLs
        continue-on-error: true
        run: |
          cd D:/bin
          for /f %i in ('where libcodec2.dll') do set VAR=%i
          for /f %i in ('dumpbin /DEPENDENTS m17-mod.exe ^| findstr .*dll ^| findstr /V K.') do ECHO F|xcopy %VAR%\..\%i .\%i
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: M17-Tools-Win-x64
          path: D:/bin/
